### ISSUE TITLE
rproxy模块只能用socket来实现吗？

### ISSUE THREAD

**Issue by Air-Zhuang** [daoye/goudan#2]
rproxy模块只能用socket来实现吗？能否替换成其他比较通俗易懂的模块

**Comment by daoye** [comment]
用socket实现是最简单的办法， rproxy只需要在客户端和代理服务器之间无脑转发流量即可。

**Comment by Air-Zhuang** [comment]
嗯嗯，还有个问题，假如我的代理优质，我有100个连接同时使用1991端口做代理，峰值达到200Mb/s，这种流量，socket模块顶得住不

**Comment by daoye** [comment]
性能参数我没有具体测试过，一般来说性能不光是软件层面的问题，跟运行环境也有很大关系。
rproxy目前用的是协程，理论上性能不会差。
